on: [push]

name: Rust

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Build Deps
        run: sudo apt install libusb-1.0-0-dev
      - name: setup pkg-config
        run: export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig
      - name: Install Latest Nightly
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - name: Run Cargo Build
        run: cargo build --release --all-features
  clippy_check:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Build Deps
        run: sudo apt install libusb-1.0-0-dev
      - name: setup pkg-config
        run: export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            components: clippy
      - uses: giraffate/clippy-action@v1 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
